import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F3F4F6" },
  scrollContent: { padding: 16, paddingBottom: 100 },
  title: { fontSize: 24, fontWeight: "bold", color: "#111827", marginBottom: 20 },

  section: {
    marginBottom: 20,
    backgroundColor: "#FFF",
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  label: { fontSize: 16, fontWeight: "700", color: "#111827", marginBottom: 12 },
  subLabel: { fontSize: 13, fontWeight: "500", color: "#4B5563", marginBottom: 6 },
  divider: { height: 1, backgroundColor: "#E5E7EB", marginVertical: 12 },

  input: {
    backgroundColor: "#F9FAFB",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: "#111827",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#D1D5DB",
  },

  colorRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  colorCircle: { width: 32, height: 32, borderRadius: 16 },
  colorSelected: { borderWidth: 3, borderColor: "#111827" },

  chipScroll: { flexDirection: "row", marginBottom: 16 },
  wrapRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 12 },

  chip: {
    backgroundColor: "#F3F4F6",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  chipSmall: {
    backgroundColor: "#F3F4F6",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  chipActive: { backgroundColor: "#EFF6FF", borderColor: "#3B82F6" },
  chipText: { fontSize: 14, color: "#4B5563" },
  chipTextActive: { color: "#1D4ED8", fontWeight: "bold" },

  switchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    backgroundColor: "#F9FAFB",
    padding: 10,
    borderRadius: 8,
  },
  switchText: { fontSize: 14, color: "#374151", fontWeight: "500" },

  row: { flexDirection: "row", marginBottom: 12 },

  dateButton: {
    flex: 1,
    backgroundColor: "#FFF",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#D1D5DB",
  },
  dateLabel: { fontSize: 12, color: "#6B7280", marginBottom: 4 },
  dateValueRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  dateValue: { fontSize: 16, fontWeight: "600", color: "#111827" },
  iconText: { fontSize: 16, marginRight: 4 },

  tabs: { flexDirection: "row", backgroundColor: "#F3F4F6", padding: 4, borderRadius: 8, marginBottom: 16 },
  tab: { flex: 1, paddingVertical: 8, alignItems: "center", borderRadius: 6 },
  tabActive: { backgroundColor: "#FFF", shadowColor: "#000", shadowOpacity: 0.1, elevation: 1 },
  tabText: { fontSize: 13, color: "#6B7280" },
  tabTextActive: { fontWeight: "bold", color: "#4F46E5" },

  weekRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 12 },
  dayCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: "#FFF",
  },
  dayCircleActive: { backgroundColor: "#4F46E5", borderColor: "#4F46E5" },
  dayText: { fontSize: 12, color: "#6B7280" },
  dayTextActive: { color: "#FFF", fontWeight: "bold" },

  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  addButtonSmall: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#EEF2FF",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  addSmallText: { color: "#4F46E5", fontWeight: "bold", fontSize: 13 },

  timesGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  timeChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    gap: 6,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  timeChipText: { fontWeight: "600", color: "#374151" },
  emptyText: { color: "#9CA3AF", fontStyle: "italic", fontSize: 14 },

  footer: { padding: 20, backgroundColor: "#FFF", borderTopWidth: 1, borderTopColor: "#E5E7EB" },
  saveButton: { backgroundColor: "#4F46E5", padding: 16, borderRadius: 12, alignItems: "center" },
  saveText: { color: "#FFF", fontSize: 16, fontWeight: "bold" },
});